### ISSUE TITLE
AutoReplace unusable

### ISSUE THREAD

**Issue by Inve1951** [p0rtL6/BetterDiscord-Plugins#1]
getting this error when trying to open the plugin's settings

![image](https://user-images.githubusercontent.com/18194808/131199477-f8542bb7-641b-4457-8bdd-394617532aec.png)

version used:  [c10a5c1](https://github.com/p0rtL6/BetterDiscord-Plugins/blob/c10a5c17b400ac91b37f418a8be5ba4a0a00ab79/AutoReplace.plugin.js)
discord release channel: 'stable'

**Comment by p0rtL6** [comment]
Download the newest version of the plugin, issue has been fixed
