### ISSUE TITLE
Will there be a fix?

### ISSUE THREAD

**Issue by l-Nuril-l** [p0rtL6/BetterDiscord-Plugins#2]
Voice Messages

**Comment by thehappylighthouse** [comment]
nop

**Comment by l-Nuril-l** [comment]
https://github.com/l-Nuril-l/Voice-Messages-Plugin-BetterDiscord

**Comment by thehappylighthouse** [comment]
oh u fixed it

> https://github.com/l-Nuril-l/Voice-Messages-Plugin-BetterDiscord

**Comment by l-Nuril-l** [comment]
require('child_process') RIP
